fix prerequisites
gazebosim/gz-rendering pull request #1054
Opened 2024-09-06 18:01 UTC by avanmalleghem

# 🦟 Bug fix

Fixes #<NUMBER>

## Summary

Fix prerequisites for 23_depth_camera_tutorial.md
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎈 Release

Preparation for <X.Y.Z> release.

Comparison to <x.y.z>: https://github.com/gazebosim/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>

Needed by <PR(s)>

## Checklist
- [ ] Asked team if this is a good time for a release
- [ ] There are no changes to be ported from the previous major version
- [ ] No PRs targeted at this major version are close to getting in
- [ ] Bumped minor for new features, patch for bug fixes
- [ ] Updated changelog
- [ ] Updated migration guide (as needed)
- [ ] Link to PR updating dependency versions in appropriate repository in [gazebo-release](https://github.com/gazebo-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-09-06 18:48 UTC, ahcorde requested changes

2024-09-06 18:48 UTC, ahcorde commented on tutorials/23_depth_camera_tutorial.md
> +```{.sh}
```suggestion
```bash
```

2024-09-06 21:46 UTC, iche033 commented
apart from the suggested changes, this looks good to me

2024-09-09 08:10 UTC, ahcorde approved these changes

2024-09-09 08:10 UTC, merged