Update code for loading normal and albedo maps from image data
gazebosim/gz-rendering pull request #1068
Opened 2024-09-18 03:12 UTC by iche033

# 🦟 Bug fix

## Summary
Currently when we load a normal map from an image data (e.g. from a glb file that has an embedded normal map texture), we upload the image data as RGBA8 with 1 mip map level. This is different from what ogre's texture manager does when it loads a normal map from file. To make the process consistent, we follow the same steps: convert to an RG signed 8 bit format then generate multiple levels of mip maps. I found that the mip map generation process made a difference to the final appearance. It helps to make the visual look smoother when viewed from a distance.

Before: The visuals appears to have some artifacts / noise, e.g more evident on the cushions behind the tables

<img width="500" alt="ionic_demo_normal_map_before" src="https://github.com/user-attachments/assets/01904588-688c-4a38-91c2-ba4d46ca8f2e">

After: visuals appear smoother

<img width="500" alt="ionic_demo_normal_map" src="https://github.com/user-attachments/assets/d7f28203-ff5f-4974-a801-b8b0f9884441">

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-09-18 08:33 UTC, ahcorde requested changes

2024-09-18 08:33 UTC, ahcorde commented on ogre2/src/Ogre2Material.cc
> +  // Here we adapte the code to load a normal map texture from an image in
```suggestion
  // Here we adapt the code to load a normal map texture from an image in
```

2024-09-18 08:33 UTC, ahcorde commented on ogre2/src/Ogre2Material.cc
> +  // _image.save(_name + ".png", 0, 1);
remove ?

2024-09-18 08:33 UTC, ahcorde commented on ogre2/src/Ogre2Material.cc
> +  for (size_t i = 1u; i < mipmaps; ++i)
include `<cstddef>`

2024-09-18 15:29 UTC, azeey commented
I just also noticed that the some of the objects in the scene appear to have a metallic look? Or at least a black band that I don't think should be there.
![image](https://github.com/user-attachments/assets/ef4205da-a264-4df9-9c3a-3b73a4d8db44)

For reference, with all lights turned off and using https://github.com/gazebosim/gz-rendering/pull/1067
![image](https://github.com/user-attachments/assets/62ebc329-b92f-4477-8991-c0b42bf08477)


And for additional reference, here's the render using Blender Cycles 
![cycles_reference](https://github.com/user-attachments/assets/6f600145-db40-41f9-9f13-6ecde822c9df)

2024-09-18 17:27 UTC, iche033 commented
> This is certainly better, but it looks like there still some differences

While testing with ogre built from source, I noticed that it also generates mip maps for the albedo textures (and maybe others) which we're not doing. It could contribute to the differences, and there could also be others.

2024-09-18 19:24 UTC, iche033 commented
> While testing with ogre built from source, I noticed that it also generates mip maps for the albedo textures (and maybe others) which we're not doing. It could contribute to the differences, and there could also be others.

Updated to also generate mip maps for albedo textures. It made subtle difference. Surfaces appear slightly smoother

<img width="500" alt="ionic_demo_normal_and_albedo" src="https://github.com/user-attachments/assets/e145092c-e496-483c-8d07-96020f2aea72">

2024-09-18 19:24 UTC, iche033 commented on ogre2/src/Ogre2Material.cc
> +  // Here we adapte the code to load a normal map texture from an image in
[615dfd5](https://github.com/gazebosim/gz-rendering/pull/1068/commits/615dfd5f52551720bdc42970a63330be43066a9f)

2024-09-18 19:24 UTC, iche033 commented on ogre2/src/Ogre2Material.cc
> +  for (size_t i = 1u; i < mipmaps; ++i)
[615dfd5](https://github.com/gazebosim/gz-rendering/pull/1068/commits/615dfd5f52551720bdc42970a63330be43066a9f)

2024-09-18 19:24 UTC, iche033 commented on ogre2/src/Ogre2Material.cc
> +  // _image.save(_name + ".png", 0, 1);
removed. [615dfd5](https://github.com/gazebosim/gz-rendering/pull/1068/commits/615dfd5f52551720bdc42970a63330be43066a9f)

2024-09-18 19:49 UTC, iche033 commented
> I just also noticed that the some of the objects in the scene appear to have a metallic look? Or at least a black band that I don't think should be there.

For that particular black band, I think at least partially it's because GI is low res and not working well. If I turn off GI, that part of the ceiling is dark since it's not lit by the spot lights. With GI enabled, it lights up part of that surface but not all, leaving the black band. If I change GI resolution to [64, 64, 64], that band is gone. However, there are still small artifacts in other places.

2024-09-19 22:36 UTC, iche033 commented
I think the appearance is now closer to the result from loading textures files. Can we get this in first?

2024-09-19 23:43 UTC, azeey approved these changes

2024-09-23 07:09 UTC, ahcorde approved these changes

2024-09-23 07:09 UTC, merged