Visualize Frustum
gazebosim/gz-rendering pull request #1095
Opened 2024-12-26 11:25 UTC by BA-Utkarsh

# 🎉 New feature

## Summary
This PR mainly adds the visualization of Frustum.
We could see it was present in gazebo classic and from gazebo garden onwards the plugin/feature is not available.

## Test it
$ Build gazebo from source.
$ . install/setup.sh
$ gz sim examples/worlds/visualize_frustum.sdf

## Test Ref images,
1. Play the simulation.
![frustum-1](https://github.com/user-attachments/assets/fef2b73b-e838-4d59-aa06-9c725fbef2ba)

2. Select the topic from scroll down.
![frustum-2](https://github.com/user-attachments/assets/df28d6c7-6f7e-4379-b123-8906a5c1809c)

3. Refresh it to get the "logical_camera/frustum" topic.
![frustum-3](https://github.com/user-attachments/assets/ae43d9c8-6c57-43d0-9420-d11c3280d277)

4. Subcriibed to "logical_camera/frustum".
![frustum-4](https://github.com/user-attachments/assets/70cf896e-56f7-4604-993b-a0d11a48fd68)

5. Final output
![frustum-6](https://github.com/user-attachments/assets/83272129-bc1a-4d97-a8c9-d3883d5c1bae)

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed
- [ ] All tests passed
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

2024-12-26 17:13 UTC, ahcorde requested changes

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/FrustumVisual.hh
> + * Copyright (C) 2015 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/FrustumVisual.hh
> +                      const gz::math::Pose3d &_pose = gz::math::Pose3d::Zero);*/
remove ?

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/FrustumVisual.hh
> +      //public: virtual bool Contains(const gz::math::Vector3d &_p) const = 0; //TO-DO
remove ?

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/FrustumVisual.hh
> +      //GZ_UTILS_IMPL_PTR(dataPtr)
remove ?

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/base/BaseFrustumVisual.hh
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/base/BaseFrustumVisual.hh
> +      protected: std::array<gz::math::Planed, 6> planes;
include `<array>`

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/base/BaseFrustumVisual.hh
> +	    return this->pose;
```suggestion
      return this->pose;
```

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/base/BaseFrustumVisual.hh
> +      return;
remove

2024-12-26 17:13 UTC, ahcorde commented on include/gz/rendering/base/BaseFrustumVisual.hh
> +#include <vector>
is vector used here ? I can see `std::array`

2024-12-26 17:13 UTC, ahcorde commented on ogre/include/gz/rendering/ogre/OgreFrustumVisual.hh
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-26 17:13 UTC, ahcorde commented on ogre/include/gz/rendering/ogre/OgreFrustumVisual.hh
> +#include <vector>
```suggestion
```

2024-12-26 17:13 UTC, ahcorde commented on ogre/include/gz/rendering/ogre/OgreFrustumVisual.hh
> +#include "gz/rendering/base/BaseFrustumVisual.hh"
```suggestion
#include <memory>

#include "gz/rendering/base/BaseFrustumVisual.hh"
```

2024-12-26 17:13 UTC, ahcorde commented on ogre/src/OgreFrustumVisual.cc
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-26 17:13 UTC, ahcorde commented on ogre/src/OgreFrustumVisual.cc
> +  	  //FrustumVisualPlane::FRUSTUM_PLANE_TOP;
remove

2024-12-26 17:13 UTC, ahcorde commented on ogre/src/OgreFrustumVisual.cc
> +  public: std::array<gz::math::Vector3d, 8> points;
include `<array>`

2024-12-26 17:13 UTC, ahcorde commented on ogre2/include/gz/rendering/ogre2/Ogre2FrustumVisual.hh
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-26 17:13 UTC, ahcorde commented on ogre2/include/gz/rendering/ogre2/Ogre2FrustumVisual.hh
> +#include <vector>
```suggestion

```

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> +  	  //FrustumVisualPlane::FRUSTUM_PLANE_TOP;
remove

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> +  public: std::vector<std::shared_ptr<Ogre2DynamicRenderable>> rayLines;
include `<vector>`

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> +  public: std::array<gz::math::Vector3d, 8> points;
include `<array>`

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> +  std::string renderSystemName =
include `<string>`

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> +  std::shared_ptr<Ogre2DynamicRenderable> renderable =
include `<memory>`

2024-12-26 17:13 UTC, ahcorde commented on ogre2/src/Ogre2FrustumVisual.cc
> +  double tanFOV2 = std::tan(this->fov() * 0.5);
include `<cmath>`

2024-12-26 17:13 UTC, ahcorde commented on src/FrustumVisual.cc
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-12-27 09:21 UTC, BA-Utkarsh commented
@ahcorde , thank you for review. I have addressed all the review comments.

2025-01-10 08:52 UTC, ahcorde requested changes
please check [linters](https://github.com/gazebosim/gz-rendering/actions/runs/12514292293/job/35270138258?pr=1095):

```
  /usr/share/gz/gz-cmake4/codecheck/cpplint.py:55: DeprecationWarning: module 'sre_compile' is deprecated
    import sre_compile
  /github/workspace/include/gz/rendering/FrustumVisual.hh:131:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/include/gz/rendering/Scene.hh:1121:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:81:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:84:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:84:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:87:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:87:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:222:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/include/gz/rendering/base/BaseFrustumVisual.hh:238:  Tab found; better to use spaces  [whitespace/tab] [1]
  /github/workspace/include/gz/rendering/base/BaseScene.hh:850:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre/include/gz/rendering/ogre/OgreScene.hh:184:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre/src/OgreFrustumVisual.cc:32:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/ogre/src/OgreFrustumVisual.cc:33:  Tab found; better to use spaces  [whitespace/tab] [1]
  /github/workspace/ogre/src/OgreFrustumVisual.cc:33:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/ogre/src/OgreFrustumVisual.cc:42:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre/src/OgreFrustumVisual.cc:94:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh:347:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:61:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:62:  Tab found; better to use spaces  [whitespace/tab] [1]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:62:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:71:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:151:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:154:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:175:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:176:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:177:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:193:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:194:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:195:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:268:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:269:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:272:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:275:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:278:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:281:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:283:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/ogre2/src/Ogre2FrustumVisual.cc:284:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  Total errors found: 37
```

2025-01-11 10:29 UTC, BA-Utkarsh commented on include/gz/rendering/FrustumVisual.hh
> + * Copyright (C) 2015 Open Source Robotics Foundation
Updated!

2025-01-11 10:29 UTC, BA-Utkarsh commented on include/gz/rendering/FrustumVisual.hh
> +                      const gz::math::Pose3d &_pose = gz::math::Pose3d::Zero);*/
Updated!

2025-01-11 10:29 UTC, BA-Utkarsh commented on include/gz/rendering/FrustumVisual.hh
> +      //public: virtual bool Contains(const gz::math::Vector3d &_p) const = 0; //TO-DO
Updated!

2025-01-11 10:29 UTC, BA-Utkarsh commented on include/gz/rendering/FrustumVisual.hh
> +      //GZ_UTILS_IMPL_PTR(dataPtr)
Updated!

2025-01-11 10:29 UTC, BA-Utkarsh commented on include/gz/rendering/base/BaseFrustumVisual.hh
> + * Copyright (C) 2020 Open Source Robotics Foundation
Updated!

2025-01-11 10:29 UTC, BA-Utkarsh commented on ogre2/src/Ogre2FrustumVisual.cc
> +  public: std::array<gz::math::Vector3d, 8> points;
Updated!

2025-01-11 10:30 UTC, BA-Utkarsh commented on ogre2/src/Ogre2FrustumVisual.cc
> +  std::string renderSystemName =
Updated!

2025-01-11 10:30 UTC, BA-Utkarsh commented on ogre2/src/Ogre2FrustumVisual.cc
> +  std::shared_ptr<Ogre2DynamicRenderable> renderable =
Updated!

2025-01-11 10:30 UTC, BA-Utkarsh commented on ogre2/src/Ogre2FrustumVisual.cc
> +  double tanFOV2 = std::tan(this->fov() * 0.5);
Updated!

2025-01-11 10:30 UTC, BA-Utkarsh commented on src/FrustumVisual.cc
> + * Copyright (C) 2020 Open Source Robotics Foundation
Updated!

2025-01-13 14:42 UTC, ahcorde approved these changes

2025-01-13 17:50 UTC, iche033 commented
Thanks for the contribution!

We follow semantic versioning and promise to maintain ABI compatibility within the same major version. Since this is targeting a release branch, we can't break ABI. The [ABI checker](https://build.osrfoundation.org/job/gz_rendering-abichecker-any_to_any-ubuntu-noble-amd64/64/API_5fABI_20report/) did pick up that the changes broke ABI (compatibility needs to be 100%). The breaking change is mainly the new `CreateFrustumVisualImpl` virtual function (which changed the vtable for BaseScene class).

Ideally we should re-target this PR to the `main` branch. Do you need this is `gz-rendering9`? If I not, let's just re-target to `main`. If you do need this in a released branch (gz-rendering9 or earlier), I can help implement a workaround to make it ABI-compatible. To do this, we should also get this in `main` first, and I'll backport this change with ABI compatibility changes.

2025-01-15 06:48 UTC, BA-Utkarsh commented
> Thanks for the contribution!
> 
> We follow semantic versioning and promise to maintain ABI compatibility within the same major version. Since this is targeting a release branch, we can't break ABI. The [ABI checker](https://build.osrfoundation.org/job/gz_rendering-abichecker-any_to_any-ubuntu-noble-amd64/64/API_5fABI_20report/) did pick up that the changes broke ABI (compatibility needs to be 100%). The breaking change is mainly the new `CreateFrustumVisualImpl` virtual function (which changed the vtable for BaseScene class).
> 
> Ideally we should re-target this PR to the `main` branch. Do you need this is `gz-rendering9`? If I not, let's just re-target to `main`. If you do need this in a released branch (gz-rendering9 or earlier), I can help implement a workaround to make it ABI-compatible. To do this, we should also get this in `main` first, and I'll backport this change with ABI compatibility changes.

Thank you @iche033 for your comment and review.
Yes, I do need it in gz-rendering9.
I shall change the target to `main`. Please help me with the ABI compatibility.

2025-01-15 06:50 UTC, BA-Utkarsh commented
@iche033 , I changed the target branch to `main`, please let me know the next action items or you will take care from here? :)

2025-01-15 18:36 UTC, iche033 commented
I created a PR (https://github.com/BA-Utkarsh/gz-rendering/pull/2) to your repo with some changes to function and variable names for consistency with the Camera class. I also added a `frustum_visual` demo, and addressed comments from other reviewers. Please take a look and merge if changes look good to you.

2025-01-16 18:03 UTC, BA-Utkarsh commented
> I created a PR ([BA-Utkarsh#2](https://github.com/BA-Utkarsh/gz-rendering/pull/2)) to your repo with some changes to function and variable names for consistency with the Camera class. I also added a `frustum_visual` demo, and addressed comments from other reviewers. Please take a look and merge if changes look good to you.

@iche033 , I have merged it.

2025-01-16 19:09 UTC, iche033 commented on ogre/src/OgreFrustumVisual.cc
> +  public: std::array<gz::math::Vector3d, 8> points;
[19aa075](https://github.com/gazebosim/gz-rendering/pull/1095/commits/19aa07588cd84d2e56e5cfc2435b4a4772671642)

2025-01-16 19:09 UTC, iche033 commented on ogre2/src/Ogre2FrustumVisual.cc
> +  public: std::vector<std::shared_ptr<Ogre2DynamicRenderable>> rayLines;
[19aa075](https://github.com/gazebosim/gz-rendering/pull/1095/commits/19aa07588cd84d2e56e5cfc2435b4a4772671642)

2025-01-16 21:43 UTC, iche033 approved these changes

2025-01-16 21:46 UTC, merged