Global illumination VCT & CI VCT
gazebosim/gz-rendering pull request #675
Opened 2022-07-18 00:10 UTC by darksylinc

# 🦟 Bug fix

Fixes #435 

## Summary

This PR adds Real Time Global Illumination based on one of these two techniques:

 1. VCT (Voxel Cone Tracing)
 2. CI VCT (Cascaded Image Voxel Cone Tracing)

VCT can be more accurate but likes static objects (static objects can bounce GI, while dynamic objects can only receive).

CI VCT can be less accurate, but it is much faster dealing with objects and deal with very large scenes (and adapt more easily to any of them) and even though it prefers static objects, you can force all objects to bounce GI and it may just work. CI VCT is still under development on the Ogre-Next side because real time global illumination is still an unsolved problem being actively (and heavily) researched on.

This PR needs Ogre 2.3 PR to be merged first.

A sample showing how to use both techniques has been added.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-07-18 08:29 UTC, ahcorde requested changes

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/GlutWindow.cc
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/GlutWindow.cc
> +        std::cout << visual->Name() << "\n";
```suggestion
        std::cout << "Selected visual at position: ";
                  << g_mouse.x << " " << g_mouse.y << ": ";
                  << visual->Name() << "\n";
```

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/GlutWindow.cc
> +        std::cout << g_mouse.x << " " << g_mouse.y << std::endl;
```suggestion
        std::cout << "No visual found at position: ";
                  << g_mouse.x << " " << g_mouse.y << std::endl;
```

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/GlutWindow.hh
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/Main.cc
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/Main.cc
> +  // gi->SetDebugVisualization(GlobalIlluminationVct::DVM_Lighting);
remove

2022-07-18 08:29 UTC, ahcorde commented on examples/global_illumination/Main.cc
> +      // std::cout << ex.what() << std::endl;
remove

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/GlobalIlluminationBase.hh
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/GlobalIlluminationCiVct.hh
> +    /// \param[in] _stepSize
document?

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/GlobalIlluminationCiVct.hh
> +    /// we will clone its settings.
```suggestion
    /// we will clone its settings.
    /// \return
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/GlobalIlluminationVct.hh
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/NativeWindow.hh
> + * Copyright (C) 2015 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2021 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/Scene.hh
> +      /// \param[in] _name Name of the new GI VCT solution
```suggestion
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/Scene.hh
> +      /// \param[in] _name Name of the new GI CIVCT solution
```suggestion
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/base/BaseGlobalIlluminationVct.hh
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on include/gz/rendering/base/BaseNativeWindow.hh
> + * Copyright (C) 2015 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on ogre2/include/gz/rendering/ogre2/Ogre2GlobalIlluminationVct.hh
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on ogre2/include/gz/rendering/ogre2/Ogre2NativeWindow.hh
> + * Copyright (C) 2018 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on ogre2/src/CMakeLists.txt
> +
force debug ? can we remove this ?

2022-07-18 08:29 UTC, ahcorde commented on ogre2/src/Ogre2GlobalIlluminationVct.cc
> + * Copyright (C) 2021 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-18 08:29 UTC, ahcorde commented on ogre2/src/Ogre2NativeWindow.cc
> + * Copyright (C) 2018 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2022 Open Source Robotics Foundation
```

2022-07-30 22:27 UTC, darksylinc commented
Ahhhh!!! Finally!

Now that Ogre 2.3 PR has been merged, I rebased the changes to main

I see @ahcorde left some feedback already that I didn't see for some reason. I have to go through each one of them.

2022-08-05 02:30 UTC, iche033 reviewed
Did a quick first pass. Examples work for me! I see reflections in the visuals:

![gz_rendering_gi](https://user-images.githubusercontent.com/4000684/182988464-192c469d-5af1-42f2-a318-c39391d3f572.png)

Can you add some unit tests for the new Global Illumination classes?

2022-08-05 16:45 UTC, darksylinc commented
> Can you add some unit tests for the new Global Illumination classes?

I have no problem with that but I have to ask... is there something you have in mind? Like _what / how_ should I test?

2022-08-05 19:08 UTC, chapulina commented
Removed the `Garden` label because we're past feature freeze ❄️ .

This PR can either be merged into `main` and backported to `gz-rendering7` after the stable release, or retargeted to `gz-rendering7` and merged after the stable release (i.e. October).

2022-08-05 19:42 UTC, darksylinc commented
> Removed the Garden label because we're past feature freeze

That's fine. I received an email from Ian about this news and I agree.

It otherwise feels too rushed. It's a lot of changes that could use feedback, testing, etc

2022-08-08 20:57 UTC, iche033 commented
> > Can you add some unit tests for the new Global Illumination classes?
> 
> I have no problem with that but I have to ask... is there something you have in mind? Like _what / how_ should I test?

I'm thinking of simple unit tests for testing the GI APIs. For example:

```cpp
  auto gi = _scene->CreateGlobalIlluminationVct();
  const uint32_t resolution[3]{ 128u, 128u, 32u };
  const uint32_t octantCount[3]{ 4, 4, 2 };
  gi->SetResolution(resolution);
  gi->SetAnisotropic(true);
  gi->SetHighQuality(false);
  gi->SetThinWallCounter(1.0f);
  gi->SetOctantCount(octantCount);
  gi->SetAnisotropic(false);
  gi->Build();
```
Just add checks to make sure the values are set correctly


```cpp
  EXPECT_EQ(128u, gi->Resolution()[0]);
  EXPECT_EQ(128u, gi->Resolution()[1]);
  EXPECT_EQ(132u, gi->Resolution()[2]);
  EXPECT_TRUE(gi->Anisotropic());
  ...
```

2022-11-14 19:48 UTC, azeey commented
waiting on version bumps

2022-12-21 22:40 UTC, darksylinc commented
1. Thanks. I'm with high fever so I'm lying down.
2. As for the crash, it's either an old OgreNext version, or it was already unloaded by the time it gets called

2022-12-21 22:56 UTC, iche033 commented
> 1. Thanks. I'm with high fever so I'm lying down.
> 2. As for the crash, it's either an old OgreNext version, or it was already unloaded by the time it gets called

Get some rest and take care! No hurry. Thanks for the tip. I'll look into it afterwards.

2022-12-22 00:44 UTC, iche033 commented
> 2. As for the crash, it's either an old OgreNext version, or it was already unloaded by the time it gets called

alright this should be fixed. Turns out it's just the `exit` call in the demo causing resources to not clean up properly.  [73d0760](https://github.com/gazebosim/gz-rendering/pull/675/commits/73d0760b084f5e028a820abbf34d4ef40b2a4ade).

2022-12-22 02:16 UTC, iche033 approved these changes

2022-12-22 19:07 UTC, merged

2022-12-22 20:23 UTC, iche033 commented
While testing the GI gui plugins in https://github.com/gazebosim/gz-sim/pull/1597, I ran into a crash with GI CiVct. I'm able to reproduce it using with the `global_illumination` example after changing the [`GI_METHOD`](https://github.com/gazebosim/gz-rendering/blob/main/examples/global_illumination/GiConfig.hh#L17) value to something other than `1`

here's the backtrace:

<details><summary>backtrace</summary>

```gdb

Thread 1 "global_illumina" received signal SIGSEGV, Segmentation fault.
0x00007ffff1edd966 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
(gdb) bt
#0  0x00007ffff1edd966 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#1  0x00007ffff1edda50 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#2  0x00007ffff1efc79e in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#3  0x00007ffff1e9a6ca in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#4  0x00007ffff1edcafa in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#5  0x00007ffff1e9aadd in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#6  0x00007ffff1eed245 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#7  0x00007ffff1f3185c in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#8  0x00007ffff1e90b39 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#9  0x00007ffff1e94941 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#10 0x00007ffff28883e8 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#11 0x00007ffff2892f00 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.85.02
#12 0x00007ffff1035b0a in Ogre::GLSLShader::compile(bool) () from /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/RenderSystem_GL3Plus.so
#13 0x00007ffff102945e in Ogre::GLSLMonolithicProgram::compileAndLink() () from /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/RenderSystem_GL3Plus.so
#14 0x00007ffff1029b1b in Ogre::GLSLMonolithicProgram::activate() () from /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/RenderSystem_GL3Plus.so
#15 0x00007ffff10272f9 in Ogre::GLSLMonolithicProgramManager::getActiveMonolithicProgram() () from /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/RenderSystem_GL3Plus.so
#16 0x00007ffff14a1cf4 in Ogre::HlmsCompute::dispatch(Ogre::HlmsComputeJob*, Ogre::SceneManager*, Ogre::Camera*) ()
   from /usr/lib/x86_64-linux-gnu/OGRE-2.3/libOgreNextMain.so.2.3.1
#17 0x00007ffff4729b65 in Ogre::VctImageVoxelizer::build(Ogre::SceneManager*) () from /usr/lib/x86_64-linux-gnu/OGRE-2.3/libOgreNextHlmsPbs.so.2.3.1
#18 0x00007ffff472b044 in Ogre::VctImageVoxelizer::buildRelative(Ogre::SceneManager*, int, int, int, unsigned int, unsigned int, unsigned int) ()
   from /usr/lib/x86_64-linux-gnu/OGRE-2.3/libOgreNextHlmsPbs.so.2.3.1
#19 0x00007ffff47237c5 in Ogre::VctCascadedVoxelizer::update(Ogre::SceneManager*) () from /usr/lib/x86_64-linux-gnu/OGRE-2.3/libOgreNextHlmsPbs.so.2.3.1
#20 0x00007ffff1a2a830 in gz::rendering::v8::Ogre2GlobalIlluminationCiVct::Build (this=0x555556e0bc50)
    at /home/ian/code/gz_h_ws/src/gz-rendering/ogre2/src/Ogre2GlobalIlluminationCiVct.cc:403
#21 0x000055555555cfdb in buildScene(std::shared_ptr<gz::rendering::v8::Scene>) ()
#22 0x000055555555df3a in createCamera(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#23 0x000055555555e44a in main ()
```

</details>

2022-12-22 20:31 UTC, darksylinc commented
Does Ogre.log say something useful?
What's your NV card and what (proprietary) driver version are you using?

2022-12-22 21:25 UTC, iche033 commented
I have nvidia drivers 510 installed through Ubuntu (Jammy)

```
ii  nvidia-driver-510                                 510.85.02-0ubuntu0.22.04.2                 amd64        NVIDIA driver metapackage
```

here's my ogre log. It's does not reveal much though

<details><summary>ogre2.log</summary>

```
13:21:54: Creating resource group General
13:21:54: Creating resource group Internal
13:21:54: Creating resource group Autodetect
13:21:54: SceneManagerFactory for type 'DefaultSceneManager' registered.
13:21:54: Registering ResourceManager for type Material
13:21:54: Registering ResourceManager for type Mesh
13:21:54: Registering ResourceManager for type Mesh2
13:21:54: Registering ResourceManager for type OldSkeleton
13:21:54: MovableObjectFactory for type 'ParticleSystem' registered.
13:21:54: ArchiveFactory for archive type FileSystem registered.
13:21:54: ArchiveFactory for archive type Zip registered.
13:21:54: ArchiveFactory for archive type EmbeddedZip registered.
13:21:54: DDS codec registering
13:21:54: FreeImage version: 3.18.0
13:21:54: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
13:21:54: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,psb,cut,xbm,xpm,gif,hdr,g3,sgi,rgb,rgba,bw,exr,j2k,j2c,jp2,pfm,pct,pict,pic,3fr,arw,bay,bmq,cap,cine,cr2,crw,cs1,dc2,dcr,drf,dsc,dng,erf,fff,ia,iiq,k25,kc2,kdc,mdc,mef,mos,mrw,nef,nrw,orf,pef,ptx,pxn,qtk,raf,raw,rdc,rw2,rwl,rwz,sr2,srf,srw,sti,x3f,webp,jxr,wdp,hdp
13:21:54: ETC codec registering
13:21:54: OITD codec registering
13:21:54: Registering ResourceManager for type HighLevelGpuProgram
13:21:54: MovableObjectFactory for type 'Decal' registered.
13:21:54: MovableObjectFactory for type 'InternalCubemapProbe' registered.
13:21:54: MovableObjectFactory for type 'Entity' registered.
13:21:54: MovableObjectFactory for type 'Item' registered.
13:21:54: MovableObjectFactory for type 'Light' registered.
13:21:54: MovableObjectFactory for type 'Rectangle2Dv2' registered.
13:21:54: MovableObjectFactory for type 'BillboardSet' registered.
13:21:54: MovableObjectFactory for type 'ManualObject2' registered.
13:21:54: MovableObjectFactory for type 'BillboardChain' registered.
13:21:54: MovableObjectFactory for type 'RibbonTrail' registered.
13:21:54: MovableObjectFactory for type 'WireAabb' registered.
13:21:54: *-*-* OGRE Initialising
13:21:54: *-*-* Version 2.3.1 (Daedalus)
13:21:54: OverlayElementFactory for type Panel registered.
13:21:54: OverlayElementFactory for type BorderPanel registered.
13:21:54: OverlayElementFactory for type TextArea registered.
13:21:54: Registering ResourceManager for type Font
13:21:54: Loading library /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/RenderSystem_GL3Plus.so
13:21:54: Installing plugin: GL 3+ RenderSystem
13:21:54: OpenGL 3+ Rendering Subsystem created.
13:21:54: Found Num EGL Devices: 3
13:21:54: EGL Device: EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_drm_render_node EGL_EXT_device_persistent_id #0 /dev/dri/card0
13:21:54: Trying to init device: EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_drm_render_node EGL_EXT_device_persistent_id #0 /dev/dri/card0...
13:21:54: Created GL 4.5 context for device EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_drm_render_node EGL_EXT_device_persistent_id #0 /dev/dri/card0
13:21:54: Destroying device: EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_drm_render_node EGL_EXT_device_persistent_id #0 /dev/dri/card0...
13:21:54: EGL Device: EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0
13:21:54: Trying to init device: EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0...
13:21:54: OGRE EXCEPTION(3:RenderingAPIException): eglInitialize failed for device EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0 in EGLSupport::getGLDisplay at ./RenderSystems/GL3Plus/src/windowing/EGL/PBuffer/OgreEglPBufferSupport.cpp (line 320)
13:21:54: OGRE EXCEPTION(3:RenderingAPIException): eglInitialize failed for device EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0 in EGLSupport::getGLDisplay at ./RenderSystems/GL3Plus/src/windowing/EGL/PBuffer/OgreEglPBufferSupport.cpp (line 320)
13:21:54: Destroying device: EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0...
13:21:54: EGL Device: EGL_MESA_device_software EGL_EXT_device_drm_render_node #2
13:21:54: Trying to init device: EGL_MESA_device_software EGL_EXT_device_drm_render_node #2...
13:21:54: Created GL 4.5 context for device EGL_MESA_device_software EGL_EXT_device_drm_render_node #2
13:21:54: Destroying device: EGL_MESA_device_software EGL_EXT_device_drm_render_node #2...
13:21:54: Plugin successfully installed
13:21:54: Loading library /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/Plugin_ParticleFX.so
13:21:54: Installing plugin: ParticleFX
13:21:54: Particle Emitter Type 'Point' registered
13:21:54: Particle Emitter Type 'Box' registered
13:21:54: Particle Emitter Type 'Ellipsoid' registered
13:21:54: Particle Emitter Type 'Cylinder' registered
13:21:54: Particle Emitter Type 'Ring' registered
13:21:54: Particle Emitter Type 'HollowEllipsoid' registered
13:21:54: Particle Affector Type 'LinearForce' registered
13:21:54: Particle Affector Type 'ColourFader' registered
13:21:54: Particle Affector Type 'ColourFader2' registered
13:21:54: Particle Affector Type 'ColourImage' registered
13:21:54: Particle Affector Type 'ColourInterpolator' registered
13:21:54: Particle Affector Type 'Scaler' registered
13:21:54: Particle Affector Type 'Rotator' registered
13:21:54: Particle Affector Type 'DirectionRandomiser' registered
13:21:54: Particle Affector Type 'DeflectorPlane' registered
13:21:54: Plugin successfully installed
13:21:54: CPU Identifier & Features
13:21:54: -------------------------
13:21:54:  *   CPU ID: GenuineIntel: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
13:21:54:  *   Logical cores: 12
13:21:54:  *      SSE: yes
13:21:54:  *     SSE2: yes
13:21:54:  *     SSE3: yes
13:21:54:  *      MMX: yes
13:21:54:  *   MMXEXT: yes
13:21:54:  *    3DNOW: no
13:21:54:  * 3DNOWEXT: no
13:21:54:  *     CMOV: yes
13:21:54:  *      TSC: yes
13:21:54:  *      FPU: yes
13:21:54:  *      PRO: yes
13:21:54:  *       HT: no
13:21:54: -------------------------
13:21:54: ******************************
*** Starting GLX Subsystem ***
******************************
13:21:54: GL3PlusRenderSystem::_createRenderWindow "OgreWindow(0)_60817409", 1x1 windowed  miscParams: FSAA=0 border=none contentScalingFactor=1.000000 gamma=Yes parentWindowHandle=60817409 stereoMode=Frame Sequential 
13:21:54: Created GL 4.5 context
13:21:55: GLXWindow::create used FBConfigID = 165
13:21:55: GL Version = 4.5.0.0
13:21:55: GL_VERSION = 4.5.0 NVIDIA 510.85.02
13:21:55: GL_VENDOR = NVIDIA Corporation
13:21:55: GL_RENDERER = NVIDIA GeForce GTX 1070/PCIe/SSE2
13:21:55: GL_EXTENSIONS = 
13:21:55: GL_AMD_multi_draw_indirect
13:21:55: GL_AMD_seamless_cubemap_per_texture
13:21:55: GL_AMD_vertex_shader_viewport_index
13:21:55: GL_AMD_vertex_shader_layer
13:21:55: GL_ARB_arrays_of_arrays
13:21:55: GL_ARB_base_instance
13:21:55: GL_ARB_bindless_texture
13:21:55: GL_ARB_blend_func_extended
13:21:55: GL_ARB_buffer_storage
13:21:55: GL_ARB_clear_buffer_object
13:21:55: GL_ARB_clear_texture
13:21:55: GL_ARB_clip_control
13:21:55: GL_ARB_color_buffer_float
13:21:55: GL_ARB_compressed_texture_pixel_storage
13:21:55: GL_ARB_conservative_depth
13:21:55: GL_ARB_compute_shader
13:21:55: GL_ARB_compute_variable_group_size
13:21:55: GL_ARB_conditional_render_inverted
13:21:55: GL_ARB_copy_buffer
13:21:55: GL_ARB_copy_image
13:21:55: GL_ARB_cull_distance
13:21:55: GL_ARB_debug_output
13:21:55: GL_ARB_depth_buffer_float
13:21:55: GL_ARB_depth_clamp
13:21:55: GL_ARB_depth_texture
13:21:55: GL_ARB_derivative_control
13:21:55: GL_ARB_direct_state_access
13:21:55: GL_ARB_draw [...]

2022-12-22 22:39 UTC, AllianceDarkSylinc commented
I'm reviewing the data and this _might_ be an OgreNext bug.

The CiVct is already very taxing on resource limits imposed by GL3+ and thus is very hard to support.

Are you able to run it if you force Vulkan? (set `public: gz::rendering::GraphicsAPI graphicsAPI{GraphicsAPI::OPENGL};` to VULKAN instead)

2022-12-22 22:42 UTC, darksylinc commented
I'm reviewing the data and this _might_ be an OgreNext bug.

The CiVct is already very taxing on resource limits imposed by GL3+ and thus is very hard to support.

Are you able to run it if you force Vulkan? (set `public: gz::rendering::GraphicsAPI graphicsAPI{GraphicsAPI::OPENGL};` to VULKAN instead)

2022-12-22 22:58 UTC, iche033 commented
> Are you able to run it if you force Vulkan? (set public: gz::rendering::GraphicsAPI graphicsAPI{GraphicsAPI::OPENGL}; to VULKAN instead)

cool, just tested with vulkan and CiVct works