Mjcarroll/anchor virtual
gazebosim/gz-rendering pull request #708
Opened 2022-08-17 13:38 UTC by mjcarroll

# 🦟 Bug fix

Based on https://github.com/gazebosim/gz-rendering/issues/702#issuecomment-1217673602

## Summary

We have some classes defined in headers that need to have at least one virtual method implemented in a `cc` file.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-08-17 15:03 UTC, ahcorde requested changes
```
  /github/workspace/include/gz/rendering/ArrowVisual.hh:35:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
  /github/workspace/include/gz/rendering/BoundingBox.hh:53:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
```

2022-08-18 14:07 UTC, mjcarroll commented
@osrf-jenkins retest this please

2022-08-24 23:59 UTC, iche033 commented on include/gz/rendering/Grid.hh
> +      public: virtual ~Grid() = 0;
should this be pure virtual?

2022-08-29 17:16 UTC, mjcarroll commented on include/gz/rendering/Grid.hh
> +      public: virtual ~Grid() = 0;
It should not, rolled back.

2022-08-30 00:09 UTC, iche033 approved these changes

2022-08-31 18:47 UTC, merged