Fix transparency over heightmap
gazebosim/gz-rendering pull request #811
Opened 2023-01-26 19:30 UTC by iche033

# 🦟 Bug fix

Fixes https://github.com/gazebosim/gz-rendering/issues/789

## Summary

Semi-transparent objects were always rendered behind the heightmap as seen in #789. This PR fixes the issue by setting a new render queue for objects with transparency as recommended in https://forums.ogre3d.org/viewtopic.php?t=96950

To test with gazebo:

1. launch gazebo (fortress) with the heightmap world:

```sh
ign gazebo -v 4 heightmap.sdf
```

1. Select Translate tool and click on any of the models. You should see the RGB axes rendered properly over the heightmap.

1. Right click on the model -> View > Transparent. The model should also be rendered properly over heightmap

![transparency_over_heightmap](https://user-images.githubusercontent.com/4000684/214931595-f7351864-92c5-44c0-990b-3b6797d5c2ff.png)

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-01-26 22:20 UTC, ahcorde requested changes

2023-01-26 22:20 UTC, ahcorde commented on ogre2/src/Ogre2Mesh.cc
> +    auto datablock =
check datablock ?

2023-01-26 22:20 UTC, ahcorde commented on test/integration/heightmap.cc
> +  // Test: the scene consists of red background, semi-transprent green box
```suggestion
  // Test: the scene consists of red background, semi-transparent green box
```

2023-01-26 22:20 UTC, ahcorde commented on test/integration/heightmap.cc
> +              << "' is not supported" << std::endl;
```suggestion
    igndbg << "Engine '" << _renderEngine
           << "' is not supported" << std::endl;
```

2023-01-26 22:20 UTC, ahcorde commented on test/integration/heightmap.cc
> +  desc.SetSize({ 17, 17, 7.0 });
```suggestion
  desc.SetSize({17, 17, 7.0});
```

2023-01-26 23:30 UTC, iche033 commented on test/integration/heightmap.cc
> +  desc.SetSize({ 17, 17, 7.0 });
[f33d5c2](https://github.com/gazebosim/gz-rendering/pull/811/commits/f33d5c21898b95303c9fd7e2ab21fd2091d4a88d)

2023-01-26 23:30 UTC, iche033 commented on test/integration/heightmap.cc
> +              << "' is not supported" << std::endl;
[f33d5c2](https://github.com/gazebosim/gz-rendering/pull/811/commits/f33d5c21898b95303c9fd7e2ab21fd2091d4a88d)

2023-01-26 23:30 UTC, iche033 commented on test/integration/heightmap.cc
> +  // Test: the scene consists of red background, semi-transprent green box
fixed. [f33d5c2](https://github.com/gazebosim/gz-rendering/pull/811/commits/f33d5c21898b95303c9fd7e2ab21fd2091d4a88d)

2023-01-26 23:30 UTC, iche033 commented on ogre2/src/Ogre2Mesh.cc
> +    auto datablock =
yep, added check. [f33d5c2](https://github.com/gazebosim/gz-rendering/pull/811/commits/f33d5c21898b95303c9fd7e2ab21fd2091d4a88d)

2023-01-27 00:05 UTC, ahcorde requested changes

2023-01-27 00:05 UTC, ahcorde commented on ogre2/src/Ogre2Mesh.cc
> +    if (databock)
```suggestion
    if (datablock)
```

2023-01-27 00:14 UTC, iche033 commented on ogre2/src/Ogre2Mesh.cc
> +    if (databock)
oops fixed. [3312c33](https://github.com/gazebosim/gz-rendering/pull/811/commits/3312c335cd7856d09b46dcdf9772d56747ceb140)

2023-01-27 08:30 UTC, ahcorde approved these changes

2023-01-27 18:15 UTC, merged