Forward port 3 to 6, Jan 29 2023
gazebosim/gz-rendering pull request #815
Opened 2023-01-29 18:35 UTC by nkoenig

# ➡️ Forward port

Port ign-rendering3 to ign-rendering6

Branch comparison: [https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>](https://github.com/gazebosim/gz-rendering/compare/ign-rendering6...ign-rendering3)

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2023-01-30 23:49 UTC, iche033 commented
Did a first pass review. Started fixing warnings and tests in https://github.com/gazebosim/gz-rendering/pull/819

2023-02-01 15:18 UTC, ahcorde requested changes
conflicts

2023-02-01 18:18 UTC, iche033 commented on Changelog.md
> +    * [Pull request #213](https://github.cohttps://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>m/ignitionrobotics/ign-rendering/pull/213)
revert this change?

2023-02-01 22:26 UTC, nkoenig commented on Changelog.md
> +    * [Pull request #213](https://github.cohttps://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>m/ignitionrobotics/ign-rendering/pull/213)
Done

2023-02-02 18:14 UTC, iche033 approved these changes
looks good to me. Demos are working fine

2023-02-02 18:25 UTC, ahcorde approved these changes

2023-02-02 19:40 UTC, merged