Fix repeatedly loading engine when calling sceneFromFirstEngine
gazebosim/gz-rendering pull request #961
Opened 2024-01-19 21:32 UTC by iche033

# 🦟 Bug fix

Fixes #959

## Summary

Added an better checks to make sure we return the engine if it was already previously loaded instead of loading the engine again.

To test:

```
gz sim -s -r -v3 --iterations 50 model_photo_shoot.sdf
```

and the following msg should now be only printed once:

```
[Msg] Loading plugin [gz-rendering-ogre2]
```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-01-19 21:48 UTC, ahcorde approved these changes

2024-01-19 21:49 UTC, ahcorde requested changes
these test are failing

```
  	202 - UNIT_RenderEngineManager_TEST_ogre_gl3plus (SEGFAULT)
  	204 - UNIT_RenderEngineManager_TEST_ogre2_gl3plus (SEGFAULT)
  	206 - UNIT_RenderingIface_TEST_ogre_gl3plus (SEGFAULT)
  	208 - UNIT_RenderingIface_TEST_ogre2_gl3plus (SEGFAULT)
```

2024-01-19 23:46 UTC, iche033 commented
> these test are failing

Should be fixed by [e297225](https://github.com/gazebosim/gz-rendering/pull/961/commits/e297225e300a044bf28cc3fa63e9535fc306c631)

2024-01-22 08:52 UTC, ahcorde approved these changes

2024-01-22 18:04 UTC, merged